# Generated by Django 3.2.21 on 2023-10-01 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('videoapi', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='transcription',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
