# Generated by Django 3.2.21 on 2023-10-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapi', '0004_video_transcription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='transcription',
            field=models.TextField(null=True),
        ),
    ]
