# Generated by Django 3.2.21 on 2023-10-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapi', '0005_alter_video_transcription'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
