# Generated by Django 3.2.21 on 2023-10-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapi', '0006_video_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(default='untitled_video', max_length=1000),
        ),
    ]
