# Generated by Django 3.2.21 on 2023-10-02 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoapi', '0007_alter_video_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
    ]
