# Generated by Django 3.2.21 on 2023-10-03 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapi', '0008_remove_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default='untitled_video', max_length=1000),
        ),
    ]
